### ISSUE TITLE
How to highlight based on multiple modifiers at once?

### ISSUE THREAD

**Issue by RedBeard0531** [theHamsta/nvim-semantic-tokens#2]
If I understand correctly a variable with both `readOnly` and `fileScope` will be end up with up to 3 highlight groups applied to it: `Variable`, `ReadOnlyVariable` and `FileScopeVariable`. That seems to assume that all modifiers are independent, but I don't think that always applies. I may want to highlight `ReadOnlyFileScopeVariable` specially, or at least differently from both `ReadOnlyFunctionScopeVariable` and (mutable) `FileScopeVariable`. That doesn't seem to be possible with your current table-based approach.

One option would be to have a user-supplied function like `highlightGroups(fileType, tokenKind, modifierList) -> optional<highlightGroupList>` and then fall back to the simple table-based approach if that returns nil. That allows fine tuning for "interesting" cases while still using a simple declarative style for normal cases. It also allows useful but non-trivial logic like looking for variables tagged with `fileScope` without `readOnly` and highlighting them `MutableGlobalVariable` (which is really the case I'd want to highlight).

If there is already some way in (neo)vim to color based on multiple highlight groups rather than just one, that would also work, but as far as I know, they are independent.

**Comment by theHamsta** [comment]
I've came to the conclusion that it is too complex to provide one implementation that fits all use cases as there are so many different combinations of modifiers+tokens. Your idea of this function sounds good, It could just replace this code region:

https://github.com/theHamsta/nvim-semantic-tokens/blob/master/lua/nvim-semantic-tokens.lua#L71-L81

**Comment by theHamsta** [comment]
I've went with a slightly different interface: https://github.com/theHamsta/nvim-semantic-tokens/issues/2
