### ISSUE TITLE
inactive regions?

### ISSUE THREAD

**Issue by mellery451** [theHamsta/nvim-semantic-tokens#23]
can someone suggest how to make this all work for inactive regions (e.g. proprocessor inactive chunks)? I think it would rely on clangd features in https://reviews.llvm.org/D67536. Will these get mapped to a specific hl group by this plugin, or is something else required? Thanks.

**Comment by theHamsta** [comment]
You can use hlgroup `LspComment` to give those regions a highlight. Semantic tokens has now been merged into master. Neovim nightly will now do it automatically with highlight `@comment`

**Comment by theHamsta** [comment]
At least, this worked for inactive ifdefs. If they use a separate token or modifier you can use the table highlighter.
