### ISSUE TITLE
Can you provide an example of this working?

### ISSUE THREAD

**Issue by jdknox** [theHamsta/nvim-semantic-tokens#24]
I installed the latest nightly neovim, put this plugin in my plugins/start directory, pasted the [setup code from the README.md](https://github.com/theHamsta/nvim-semantic-tokens) file, and tried the following in a C file with `clangd` running:

`:hi link LspEnumMember Keyword`
`:hi link LspEnum String`
etc., using suggestions from the [doc file on highlighting](https://github.com/theHamsta/nvim-semantic-tokens/blob/master/doc/nvim-semantic-tokens.txt).

Nothing changes in my file.  No color highlighting changes.

lsp.log shows `ASTWorker building file /.../t.c`

output of `:lua =vim.lsp.semantic_tokens` shows things like
```
{
  end_col = 18,
  extmark_added = true,
  line = 25,
  modifiers = { "declaration", "readonly", "fileScope" },
  start_col = 4,
  type = "enumMember"
}
```
and
```
{
  end_col = 14,
  extmark_added = true,
  line = 33,
  modifiers = { "globalScope" },
  start_col = 5,
  type = "enum"
}
```
So it looks like the server is sending back the correct info, but the highlight links don't appear to do anything.

---

The log shows this on a `:LspRestart`:
```
--> workspace/semanticTokens/refresh(0)\n"
<-- $/cancelRequest
I[21:00:16.192] <-- textDocument/semanticTokens/full(3)\n"
<-- reply(0)\n"
--> textDocument/publishDiagnostics\n"
--> reply:textDocument/semanticTokens/full(2) 48 ms, error: Task was cancelled.
I[21:00:16.219] --> reply:textDocument/semanticTokens/full(3) 27 ms\n"
```

---

Edit: forgot to mention I'm using:
```
$ clangd --version
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```

**Comment by theHamsta** [comment]
Did you do the auto command when the language server was already started?
```
autocmd BufEnter,TextChanged <buffer> lua require 'vim.lsp.buf'.semantic_tokens_full()
```
I'm no longer planning to maintain this since Neovim now supports this functionality natively on Nightly https://github.com/neovim/neovim/pull/21100

**Comment by jdknox** [comment]
> I'm no longer planning to maintain this since Neovim now supports this functionality natively on Nightly [neovim/neovim#21100](https://github.com/neovim/neovim/pull/21100)

This works for me, but I didn't see how the highlighting worked in that merge, which is how I came across your plugin.  So, if I have semanticTokens enabled on the server, it will automatically send the `@enum`, `@struct`, etc. highlight group info for each symbol?  And how do I determine if `globalScope` is set on a symbol?

I'm trying to highlight variables that happen to be an `enum` type, but the semantic tokens just show the variable as `variable`.  The only time an `enum` is detected is when it is declared, which can just be done with tree-sitter.  Do you know if this is intended behavior?  Shouldn't semantic highlighting decorate variables with their type?

Sorry for all these questions, it's just that the docs aren't very clear on any of this.

**Comment by theHamsta** [comment]
@jdknox the upstream implementation was less flexible. At the moment it does not support modifiers an highlights every token type just with an `@` prepended. I saw that modifiers were just added. Can you have a look onto this https://github.com/neovim/neovim/pull/21390

**Comment by jdknox** [comment]
Thanks for that link.  I thought I had downloaded the latest nightly from yesterday, but somehow it was an older commit than the one you posted.

The built-in semantic modifiers work for me now.  Thanks for the help!
